### ISSUE TITLE
Graph Tab Freezes if 'Next' is clicked w/out a selection  

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/CyAN-Web#215]
Should we disable the 'Next' unless a checkbox is selected? @kathymd 

steps to reproduce:
https://recordit.co/sUxF9XFpXI

**Comment by ghost** [comment]
Oops, this is my fault. I call a function when a user clicks on a point, but I forgot to call it when a user selects using lasso. I'm glad you discovered this! I can take this and get it working.
Submit button should show instead of Next when no axes are selected, so that if there are any flags in the lasso selection, they get deleted.
