### ISSUE TITLE
Error plotting WQP points

### ISSUE THREAD

**Issue by ghost** [USGS-WiM/CyAN-Web#293]
Example parameters to recreate error:
1. Navigate to graph filters
2. Database: check GLRI and WQP
3. X-Axis: `chl_ave` for parameter and method
4. Y-Axis: `pc_ave` for paramter and method
5. `Create Graph`
6. Infinite load; see error in console

![image](https://user-images.githubusercontent.com/46943254/216431554-b7026325-ec9f-465d-87ad-a9f3dda88148.png)

Choosing WQP data doesn't always error out. For example, I was able to plot Water Temperature just fine on the map.

**Comment by lprivette** [comment]
testing locally, it looks like it's still a pandas/date-time issue.

`{"meta":{"north":90,"south":-90,"east":180,"west":-180,"min_year":1980,"max_year":2021,"include_NULL":false,"satellite_align":false,"region":[],"organization":0},"items":{"P12":["M1"]}}`

![image](https://user-images.githubusercontent.com/23640741/216460351-71b1e146-8109-493b-b04d-734ef057dc98.png)

**Comment by lprivette** [comment]
I think it's erroring when org = 0 (meaning it can come from any org) because it's hitting all the entries in the SQL statement, and converting the datetime before filtering based on the mcode/pcode selections.

Would it make sense to move the date time conversion to after the list is parsed? Regardless it seems there are still some date-time-values that causes the pandas function to fail :/

![image](https://user-images.githubusercontent.com/23640741/216470099-77b04ed4-6db7-4bc0-b91b-498cdbc70253.png)

**Comment by ChadFanguy-usgs** [comment]
@lprivette can you try the below before line 234 with the date conversion? It substrings the date_time_group field to get rid of the time which might fix it. There's still some row that have time in the db

fetched['date_time_group'] = fetched['date_time_group'].str[:10]

**Comment by lprivette** [comment]
That did fix it chad! should I add it permanently to the services or is the time something we want to remove from all db entries?

**Comment by lprivette** [comment]
@kathymd Ready for verification that the points now plot with those selections https://test.wim.usgs.gov/cyan-field-test/

**Comment by ghost** [comment]
Hooray! Works great
